# Generated by Django 2.0.7 on 2018-07-23 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('note_text', models.TextField(max_length=512)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
