# Generated by Django 2.0.7 on 2018-07-23 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='note',
            table='notes',
        ),
    ]
